[[redirects]]
  from = "/todo/"
  to = "https://acelowder-todo.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/comments/"
  to = "https://acelowder-comments.netlify.app/"
  status = 200
  force = true